name: Build and Test

on:
  push:
    branches:
      - main
      - JOB-14

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "24"

      - name: Find Ant build file
        run: find . -name build.xml -print

      - name: Build project
        run: ant -noinput -f build.xml clean jar

      - name: Run JUnit tests
        run: ant -noinput -f build.xml test
